fix: Failing to parse openjd_env and openjd_unset_env should fail session action
OpenJobDescription/openjd-sessions-for-python pull request #111
Opened 2024-03-14 20:14 UTC by sakshie95

### What was the problem/requirement? (What/Why)
When the stdout handlers in OpenJD fail to process a message, the error is logged but does not fail the action. This is intended behavior for non-functional messages (e.g. ``openjd_status`` and ``openjd_progress``). However, for functional messages such as ``openjd_env`` or ``openjd_unset_env`` which sets an environment variable in the session, we should fail the session when the stdout handler fails to process these messages since this could have adverse effects on the session action.

### What was the solution? (How)
Cancel the ongoing action when an error occurs in ``openjd_env`` or ``openjd_unset_env`` and mark the action as ``FAILED`` when the callback is sent to the session. Also to support customers an additional regex for "almost" matching env or unset_env (like whitespaces or casing issues) is also detected and cancels the action, marks it as failed back to the session.

### What is the impact of this change?
Better error handling for customers so they know if setting an env variable fails instead of hiding the error.

### How was this change tested?
Modified and ran existing unit tests. Added more tests for testing that the callback sent to the calling session marks the action as ``FAILED``
### Was this change documented?
N/A

### Is this a breaking change?
No, fix!

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-03-14 22:02 UTC, ddneilson requested changes
Just one small thing. This is great, though. Thanks for taking this on!

2024-03-14 22:02 UTC, ddneilson commented on src/openjd/sessions/_action_filter.py
> +openjd_env_actions_filter_regex = "^(openjd_env|openjd_unset_env)+"
```suggestion
openjd_env_actions_filter_regex = "^(openjd_env|openjd_unset_env)"
```

I think that we don't want the `+` here, right? That would match it one or more times.

2024-03-14 22:02 UTC, ddneilson commented on src/openjd/sessions/_action_filter.py
> +            err_message = f"Open Job Description: Unexpected error in message ({record.msg})"
Maybe "Incorrectly formatted" rather than "Unexpected error" ?

2024-03-15 00:05 UTC, sakshie95 commented on src/openjd/sessions/_action_filter.py
> +openjd_env_actions_filter_regex = "^(openjd_env|openjd_unset_env)+"
yes you are right, I will remove the `+`as  it's not required

2024-03-15 00:05 UTC, sakshie95 commented on src/openjd/sessions/_action_filter.py
> +            err_message = f"Open Job Description: Unexpected error in message ({record.msg})"
Sure thing, will update

2024-03-18 18:19 UTC, ddneilson submitted a review, later dismissed

2024-03-18 18:47 UTC, mwiebe requested changes

2024-03-18 18:47 UTC, mwiebe commented on src/openjd/sessions/_action_filter.py
> +    _callback: Callable[[ActionMessageKind, Any, bool], None]
Can you add a line to the docstring explaining this third `bool` arg?

2024-03-18 21:22 UTC, sakshie95 commented on src/openjd/sessions/_action_filter.py
> +    _callback: Callable[[ActionMessageKind, Any, bool], None]
Sure thing, added it

2024-03-18 21:23 UTC, ddneilson approved these changes

2024-03-18 21:25 UTC, mwiebe approved these changes

2024-03-18 21:37 UTC, merged