fix: Support for multi line env variables in enter env
OpenJobDescription/openjd-sessions-for-python pull request #115
Opened 2024-03-20 23:02 UTC by sakshie95

### What was the problem/requirement? (What/Why)
OpenJD silently truncates multi-line environment variable values

### What was the solution? (How)
Support two payloads modes for the openjd_env: ... message.

If the value has no special characters like newlines or unicode (I think the spec already has cases like this to duplicate here), ``openjd_env: VAR_NAME=value`` to set can be used to set the variable correctly.
In all cases, the payload can be encoded as a one-line JSON string, like ``openjd_env: "VAR_NAME=value to set \n with newlines ..."``
Another special case to validate:

Both of these payloads work, with no warning or error messages, to set an empty value. Both of these payloads are correct:

``openjd_env: VAR_NAME=``

and
``openjd_env: "VAR_NAME="``

### What is the impact of this change?
Customer can set multi line env variables.

### How was this change tested?
Yes, with unit tests.

### Was this change documented?
No, but it should be in the Release notes and probably here https://github.com/OpenJobDescription/openjd-specifications/wiki/How-Jobs-Are-Run#stdoutstderr-messages

### Is this a breaking change?
No, backwards compatible
----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-03-21 02:08 UTC, ddneilson requested changes

2024-03-21 02:08 UTC, ddneilson commented on src/openjd/sessions/_action_filter.py
> +envvar_set_regex_json = '^(")?[A-Za-z_][A-Za-z0-9_]*' "=" ".*$"  # Variable name
Based on how it's used, I suspect that it won't actually matter, but I think that the regex here is intended to be more along the lines of:
```suggestion
envvar_set_regex_json = '^"[A-Za-z_][A-Za-z0-9_]*' "=" '.*"$'  # Variable name
```

i.e.
1. No `?` for the leading double-quote; and
2. Including the terminating double-quote.

2024-03-21 02:08 UTC, ddneilson commented on test/openjd/sessions/test_session.py
> +    def test_def_via_multi_line_invalid_json_stdout(
"invalid" is on list of non-inclusive terms. Mind changing to "nonvalid" or equivalent?

2024-03-21 02:08 UTC, ddneilson commented on test/openjd/sessions/test_session.py
> +            # THEN
Can you add an assert here that verifies that the value of the environment value `FOO` has been set correctly in the Task?

e.g. have the task run the command: `f' "command"="{sys.executable}", "args"=["-c", "import os; print('FOO:'); print(os.environ.get(\'FOO\'); print('---')"]` and make sure that the value are printed as:
```
FOO:
12
34
---
```

2024-03-22 17:44 UTC, sakshie95 commented on src/openjd/sessions/_action_filter.py
> +envvar_set_regex_json = '^(")?[A-Za-z_][A-Za-z0-9_]*' "=" ".*$"  # Variable name
The ``(")?`` is for checking open and (mandatory) close quotes that's required for regex validation for a json. I tried with your suggestion as well but that doesn't work the same way for incorrectly formatted jsons

2024-03-22 17:44 UTC, sakshie95 commented on test/openjd/sessions/test_session.py
> +    def test_def_via_multi_line_invalid_json_stdout(
Sure thing!

2024-03-22 17:44 UTC, sakshie95 commented on test/openjd/sessions/test_session.py
> +            # THEN
Done

2024-03-22 18:46 UTC, sakshie95 commented on test/openjd/sessions/test_session.py
> +            # THEN
Thanks for this comment, it was really useful :)

2024-03-22 18:55 UTC, ddneilson commented on src/openjd/sessions/_action_filter.py
> +envvar_set_regex_json = '^(")?[A-Za-z_][A-Za-z0-9_]*' "=" ".*$"  # Variable name
Ah, right, incorrectly formatted JSON. Sounds good. We'll keep it then

2024-03-22 18:56 UTC, ddneilson commented on test/openjd/sessions/test_session.py
> +            # THEN
Perfect! Thank you for adding the test

2024-03-22 18:56 UTC, ddneilson approved these changes

2024-03-22 19:25 UTC, jericht approved these changes

2024-03-22 19:25 UTC, jericht commented on src/openjd/sessions/_action_filter.py
> +envvar_set_regex_json = '^(")?[A-Za-z_][A-Za-z0-9_]*' "=" ".*$"  # Variable name
Don't we need the terminating double-quote? It looks like we're currently relying on `json.loads` to throw an error, but maybe that's fine
```suggestion
envvar_set_regex_json = '^(")?[A-Za-z_][A-Za-z0-9_]*' "=" '.*"$'  # Variable name
```

2024-03-22 19:25 UTC, jericht commented on test/openjd/sessions/test_session.py
> +    @pytest.mark.usefixtures("caplog")  # builtin fixture
nit: this is not necessary since we are explicitly requested the fixture in the test function. I see this is the pattern we use in other tests here though, so we can leave this as is

2024-03-22 19:38 UTC, ddneilson commented on test/openjd/sessions/test_session.py
> +    @pytest.mark.usefixtures("caplog")  # builtin fixture
Yeah, that pattern is a me thing. When new to pytest I'd look at the function arguments and have no idea where they're coming from; the 'usefixtures' markers act as a gentile "it comes from a builtin"

2024-03-22 20:35 UTC, sakshie95 commented on src/openjd/sessions/_action_filter.py
> +envvar_set_regex_json = '^(")?[A-Za-z_][A-Za-z0-9_]*' "=" ".*$"  # Variable name
Yeah relying on a combination - regex first for determing whether it's a json or str value and then using ``json.loads`` to verify the json itself should make it full proof

2024-03-22 20:41 UTC, merged