fix!: Windows locate_executable finds wrong binary to run
OpenJobDescription/openjd-sessions-for-python pull request #141
Opened 2024-06-07 05:14 UTC by mwiebe

### What was the problem/requirement? (What/Why)

This fixes issue #140

### What was the solution? (How)

By calling a Python subprocess to run `shutil.where` instead of a cmd subprocess to run `where`.

### What is the impact of this change?

Jobs depending on binaries provided by environments will reliably find the correct one from the PATH.

### How was this change tested?

Marked as draft while testing.

### Was this change documented?

The new requirement related to this being a breaking change was added to the README.

### Is this a breaking change?

It is a breaking change, because it introduces a new requirement that when impersonating a user for subprocesses, the Python installation hosting the library can be run by the impersonated user as well.

I believe it is likely that the new requirement is already met in existing usage, as was the case for my setup.

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-06-07 14:34 UTC, ddneilson requested changes
Thanks Mark. This is helpful!

2024-06-07 14:34 UTC, ddneilson commented on src/openjd/sessions/_win32/_locate_executable.py
> +                sys.executable.lower().replace("pythonservice.exe", "python.exe"),
I think that we'll need some additional error handling now. Previously, we could be confident that the executable that we were trying to run is present. Now it's possible that it exists, but we do not have the required permission to run it. If that happens, the user will see a ["Process failed to start"](https://github.com/OpenJobDescription/openjd-sessions-for-python/blob/beeb4992dfc37ee2532fb79083819f285f4cfafc/src/openjd/sessions/_subprocess.py#L290) error in their log, but may not connect the dots as to why.

In this particular instance, we have a pretty strong idea as to why. We know that the executable exists, so being unable to run it will likely be due to permissions. I'd expect `process.exit_code` to be `None` in this case (we'll hit [here](https://github.com/OpenJobDescription/openjd-sessions-for-python/blob/beeb4992dfc37ee2532fb79083819f285f4cfafc/src/openjd/sessions/_subprocess.py#L289-L291) then [here](https://github.com/OpenJobDescription/openjd-sessions-for-python/blob/beeb4992dfc37ee2532fb79083819f285f4cfafc/src/openjd/sessions/_subprocess.py#L156-L161), so `process._returncode` will [remain `None`](https://github.com/OpenJobDescription/openjd-sessions-for-python/blob/beeb4992dfc37ee2532fb79083819f285f4cfafc/src/openjd/sessions/_subprocess.py#L92) in the [request for an exit code](https://github.com/OpenJobDescription/openjd-sessions-for-python/blob/beeb4992dfc37ee2532fb79083819f285f4cfafc/src/openjd/sessions/_subprocess.py#L101-L112)). Would you mind raising a `RuntimeError` in this case with a message to help the end user diagnose & fix the issue? (note that we have the username of the target user in `user.user`)

2024-06-07 16:03 UTC, mwiebe commented on src/openjd/sessions/_win32/_locate_executable.py
> +                sys.executable.lower().replace("pythonservice.exe", "python.exe"),
Good point! This issue was tricky to diagnose in the first place, don't want to leave the potential for something similar with the new installation requirement.

2024-06-08 00:31 UTC, mwiebe commented on src/openjd/sessions/_win32/_locate_executable.py
> +                sys.executable.lower().replace("pythonservice.exe", "python.exe"),
This is ready for another look.

2024-06-08 01:11 UTC, npmacl approved these changes, later dismissed

2024-06-10 14:54 UTC, crowecawcaw submitted a review, later dismissed

2024-06-10 15:18 UTC, ddneilson requested changes
It looks like this has broken two tests when running processes as a separate user.

```
FAILED test/openjd/sessions/test_runner_step_script.py::TestStepScriptRunner::test_run_file_in_session_dir_as_windows_user[No defined env vars] - AssertionError: assert <ScriptRunner...LED: 'failed'> == <ScriptRunner...SS: 'success'>
FAILED test/openjd/sessions/test_runner_step_script.py::TestStepScriptRunner::test_run_file_in_session_dir_as_windows_user[os_env_vars1] - AssertionError: assert <ScriptRunner...LED: 'failed'> == <ScriptRunner...SS: 'success'>FAILED test/openjd/sessions/test_runner_step_script.py::TestStepScriptRunner::test_run_file_in_session_dir_as_windows_user[No defined env vars] - AssertionError: assert <ScriptRunner...LED: 'failed'> == <ScriptRunner...SS: 'success'>
FAILED test/openjd/sessions/test_runner_step_script.py::TestStepScriptRunner::test_run_file_in_session_dir_as_windows_user[os_env_vars1] - AssertionError: assert <ScriptRunner...LED: 'failed'> == <ScriptRunner...SS: 'success'>
```

The test's output is:

```
INFO     sessions.conftest.Nr,pD,rfxD2]zH+D"$6ldTu-8fr\)N6::_logging.py:20 ----------------------------------------------
INFO     sessions.conftest.Nr,pD,rfxD2]zH+D"$6ldTu-8fr\)N6::_logging.py:21 Phase: Running action
INFO     sessions.conftest.Nr,pD,rfxD2]zH+D"$6ldTu-8fr\)N6::_logging.py:22 ----------------------------------------------
INFO     sessions.conftest.Nr,pD,rfxD2]zH+D"$6ldTu-8fr\)N6::_subprocess.py:270 Running command .\test.bat
INFO     sessions.conftest.Nr,pD,rfxD2]zH+D"$6ldTu-8fr\)N6::_subprocess.py:290 Process failed to start: [WinError 2] The system cannot find the file specified.
```

So, the change has made it so that we can no longer find the executable file if it's a script in the working directory.

We don't currently have cross-user testing in the GitHub CIs, so the way to test this is by following the instructions in https://github.com/OpenJobDescription/openjd-sessions-for-python/blob/mainline/DEVELOPMENT.md#user-impersonation-windows-based-systems

I saw these fails when running in both Windows Session ID 0 and non-zero.

The tests do not fail on mainline.

2024-06-10 16:32 UTC, mwiebe commented
I've updated the code to share that `path_var` logic between the two cases.

2024-06-10 19:11 UTC, crowecawcaw submitted a review, later dismissed

2024-06-12 14:33 UTC, ddneilson requested changes
Thanks Mark. Looks like it still fails two tests. To fix, you'll need to apply this patch:

```
> git diff
diff --git a/src/openjd/sessions/_win32/_locate_executable.py b/src/openjd/sessions/_win32/_locate_executable.py
index 3cffbfb..fd33cfe 100644
--- a/src/openjd/sessions/_win32/_locate_executable.py
+++ b/src/openjd/sessions/_win32/_locate_executable.py
@@ -117,10 +117,10 @@ def _locate_for_other_user(
                 # Command injection here is possible, but it's irrelevant. The command is running
                 # as the given user. No need for an attacker to be fancy here, they could just run
                 # the desired attack command directly in the job template.
-                "import shutil, sys\n"
+                "import shutil, sys, pathlib\n"
                 + f"cmd = shutil.which({str(command)!r}, path={path_var!r})\n"
                 + "if cmd:\n"
-                + "  print(cmd)\n"
+                + "  print(str(pathlib.Path(cmd).absolute()))\n"
                 + f"  sys.exit({exit_code_success})\n"
                 + f"sys.exit({exit_code_could_not_find_exe})\n",
             ]
```

2024-06-12 14:43 UTC, ddneilson requested changes

2024-06-12 14:43 UTC, ddneilson commented on src/openjd/sessions/_win32/_locate_executable.py
> +                "import shutil, sys\n"
```suggestion
                "import shutil, sys, pathlib\n"
```

2024-06-12 14:43 UTC, ddneilson commented on src/openjd/sessions/_win32/_locate_executable.py
> +                + "  print(cmd)\n"
```suggestion
                + "  print(str(pathlib.Path(cmd).absolute()))\n"
```

2024-06-12 15:15 UTC, ddneilson approved these changes

2024-06-12 15:17 UTC, crowecawcaw approved these changes

2024-06-12 15:21 UTC, merged