fix: Session stuck reading on STDOUT stream
OpenJobDescription/openjd-sessions-for-python pull request #162
Opened 2024-08-08 15:01 UTC by AWS-Samuel

### What was the problem/requirement? (What/Why)
If the command in a action created a grandchild process that inherits the original action process' STDOUT stream, we were at the mercy of that grandchild process closing the stream in order to end the action.

### What was the solution? (How)
Instead of waiting for the STDOUT stream to end, wait for the action subprocess to end. 

We add some buffer and grace time for situations like above so the process changes from:

1. Loop on the STDOUT stream receiving output
   - Log the STDOUT

1. Loop on the STDOUT stream receiving output
   - If the command exits then:
     - Wait 1 second for the STDOUT to close then
       - Print the 5 second gracetime warning
     - If the 5 second gracetime is up:
       - Break the loop, signal the logging thread to exit
 2. Clear the STDOUT queue, end action

### What is the impact of this change?

If a command creates a grandchild process that prints output to the original command's STDOUT stream, we now have a mechanism to exit. We also have a more clearly defined point at which a action command is done.

### How was this change tested?

Unit tests created. 

Tested on a Linux and Windows machine, using the Deadline Cloud Worker agent and the following job template:

```
specificationVersion: jobtemplate-2023-09
name: hang job
steps:
  - name: hang
    script:
      embeddedFiles:
        - name: Hang
          type: TEXT
          filename: hang.py
          data: |
            import subprocess
            import os
            import json

            PING_COMMAND = ["ping", "localhost"] + (["-t"] if os.name == "nt" else [])

            process = subprocess.Popen(
                [
                    "python",
                    "-c",
                    f'import subprocess; p=subprocess.Popen({json.dumps(PING_COMMAND)}, encoding=\"utf-8\")'
                ],
            )

      actions:
        onRun:
          command: python
          args: ["{{Task.File.Hang}}"]
```

### Was this change documented?

WIP

### Is this a breaking change?

Sort of. WIP

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-08-08 22:33 UTC, jusiskin requested changes

2024-08-08 22:33 UTC, jusiskin commented on src/openjd/sessions/_subprocess.py
> +                        process_exit_time = time.time()
We should use [`time.monotonic()`](https://docs.python.org/3/library/time.html#time.monotonic) instead of `time.time()` throughout this change to handle the edge case where the system clock is adjusted while the worker agent is running.

2024-08-08 22:33 UTC, jusiskin commented on src/openjd/sessions/_subprocess.py
> +                    break
Is the thread guaranteed to get to this check and exit the loop? I'm considering the case where a subprocess inherits the stdout descriptor, but does not emit any output.

Maybe we can verify by adding a test where the subprocess of a `LoggingSubprocess` sleeps indefinitely and writes no output to stdout.

2024-08-09 00:42 UTC, mwiebe commented on src/openjd/sessions/_subprocess.py
> +                    line = stdout_queue.get(timeout=0.25)
Have you tested tasks that are faster than this, e.g. 0.05 seconds? Do they run slower after this change?

2024-08-09 19:07 UTC, AWS-Samuel commented on src/openjd/sessions/_subprocess.py
> +                        process_exit_time = time.time()
Changed to `monotonic()`, thanks

2024-08-09 19:10 UTC, AWS-Samuel commented on src/openjd/sessions/_subprocess.py
> +                    break
I see, you're right, in this case the thread is not guaranteed to get to that check and exit. I've modified the logic to not join the thread, and added some code explaining the reasoning why. Unfortunately it seems that python does not have a good, cross-platform/version way of doing timed-out blocking reads on IO streams.  

Added the tests where the logging subprocess sleeps and emits no output

2024-08-09 20:24 UTC, AWS-Samuel commented on src/openjd/sessions/_subprocess.py
> +                    line = stdout_queue.get(timeout=0.25)
You're right, they do. I've changed the timeout to `0.001` seconds. In this case the CPU overhead does not appear to register on my system resource monitor, while the openjd overhead of running an action still dwarfs the timeout. From my benchmark tests there was no measurable difference when running a job like the following:


```
specificationVersion: jobtemplate-2023-09
name: whoami
steps:
  - name: whoami
    script:
      actions:
        onRun:
          command: whoami
```

2024-08-12 15:00 UTC, ddneilson commented on src/openjd/sessions/_subprocess.py
> +                    exit_event.set()  # When the STDOUT stream ends this will cause the thread to exit.
What happens in here if we close the `stream` as well? Does that allow the thread to exit?

2024-08-12 15:02 UTC, AWS-Samuel commented on src/openjd/sessions/_subprocess.py
> +                    exit_event.set()  # When the STDOUT stream ends this will cause the thread to exit.
I tried this and it had no effect on allowing the thread to exit.

2024-08-12 15:27 UTC, jusiskin approved these changes

2024-08-12 15:30 UTC, ddneilson approved these changes

2024-08-12 15:33 UTC, merged