feat: introduce log metadata
OpenJobDescription/openjd-sessions-for-python pull request #170
Opened 2024-09-12 16:30 UTC by AWS-Samuel

### What was the problem/requirement? (What/Why)

Consumers of the `openjd_sessions` module may want a means of filtering logs based on their contents. 

### What was the solution? (How)

In order to solve this problem, this commit introduces a `metadata` structure we can add to the `extra` kwarg when logging messages. The value provided to the `extra` kwarg must be of type `dict[str, Any]`, with the limitation that the field names cannot be an [existing attribute name in LogRecord](https://docs.python.org/3/library/logging.html#logrecord-attributes).

This commit then introduces a `LogMetadata` class which contains two properties: `log_purpose` and `log_content`

`log_purpose` is of type `LogPurpose` - an Enum which can be either `Diagnostic`, `Title` or `Output`.

`log_content` is of type `Flag` which can allows combining multiple `LogContent` values through bitwise operators in order to indicate which contents are in the logged message. 

### What is the impact of this change?

A `LogMetadata` structure becomes available to attached to logged messages, that consumers of this package can use to filter log messages based on the type of log message.

### How was this change tested?

> Have you run the unit tests?

Yes

Also began adding the metadata to existing log messages in this draft PR: https://github.com/OpenJobDescription/openjd-sessions-for-python/pull/169/commits/e36e32bf4871a5e4932f29072159c9d967ca10ba and confirmed tests still passed while the extra info was available for consumers of the package. 

### Was this change documented?

It is through the changelog. 
  
### Is this a breaking change?

No

### Does this change impact security?

No

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-09-12 16:47 UTC, ddneilson requested changes
This is great, Sam. Thanks for taking this on.

Can you also add some public documentation for this so that users of the library can discover that this extra log metadata exists? Perhaps as a docstring on the `LOG` global in this file?

For example, we communicate that there's a session_id metadata in the log messages [here](https://github.com/OpenJobDescription/openjd-sessions-for-python/blob/009737a6a02b9c048085949c85e036fa0aa210e3/src/openjd/sessions/_session.py#L178-L182).

2024-09-12 16:47 UTC, ddneilson commented on src/openjd/sessions/_logging.py
> +class OJDExtraInfo(TypedDict):
nit: I think that the `OJD` prefix is a given, since it's a private class within the `openjd-sessions` module.

```suggestion
class LogExtraInfo(TypedDict):
```

2024-09-12 17:02 UTC, ddneilson commented
Chatted offline. We'll also need to make sure that the uses of this don't clobber the `extra` that is added by the [`Session`'s `LoggerAdaptor`](https://github.com/OpenJobDescription/openjd-sessions-for-python/blob/009737a6a02b9c048085949c85e036fa0aa210e3/src/openjd/sessions/_session.py#L397). All of the logger instances that are used in this library are actually instances of that object, so we'll need to make sure that it still works as expected.

2024-09-13 19:27 UTC, AWS-Samuel commented on src/openjd/sessions/_logging.py
> +class OJDExtraInfo(TypedDict):
Amended

2024-09-13 19:29 UTC, AWS-Samuel commented
> This is great, Sam. Thanks for taking this on.
> 
> Can you also add some public documentation for this so that users of the library can discover that this extra log metadata exists? Perhaps as a docstring on the `LOG` global in this file?
> 
> For example, we communicate that there's a session_id metadata in the log messages [here](https://github.com/OpenJobDescription/openjd-sessions-for-python/blob/009737a6a02b9c048085949c85e036fa0aa210e3/src/openjd/sessions/_session.py#L178-L182).

Added, confirmed that the documentation shows up under hover text for `LOG` in my editor.

>Chatted offline. We'll also need to make sure that the uses of this don't clobber the extra that is added by the [Session's LoggerAdaptor](https://github.com/OpenJobDescription/openjd-sessions-for-python/blob/009737a6a02b9c048085949c85e036fa0aa210e3/src/openjd/sessions/_session.py#L397). All of the logger instances that are used in this library are actually instances of that object, so we'll need to make sure that it still works as expected.

Confirmed that this was causing issue, so I added an override and added a test for this.

2024-09-16 20:30 UTC, ddneilson requested changes
One small nitpick. Thanks for fixing this up, Sam.

2024-09-16 20:30 UTC, ddneilson commented on src/openjd/sessions/_logging.py
> +throughout the openjd sessions module to provide information on actions OpenJD is taking, as well as
```suggestion
throughout the openjd sessions module to provide information on actions the module is taking, as well as
```

2024-09-18 15:00 UTC, AWS-Samuel commented on src/openjd/sessions/_logging.py
> +throughout the openjd sessions module to provide information on actions OpenJD is taking, as well as
Thanks, added in latest

2024-09-19 15:06 UTC, ddneilson approved these changes

2024-09-19 15:13 UTC, moorec-aws approved these changes

2024-09-19 15:58 UTC, merged