test: upgrade docker testing compatibility to Docker 25.x
OpenJobDescription/openjd-sessions-for-python pull request #172
Opened 2024-09-18 14:36 UTC by jusiskin

### What was the problem/requirement? (What/Why)

1.  The development documentation (`DEVELOPMENT.md`) for using the docker container test workflow for POSIX user impersonation tests was not clear/accurate
2.  The scripting for using the docker container tests was not compatible with modern Docker. Attempting to build the LDAP docker image with Docker 25.x failed because it could not write to `/etc/hosts` which is mounted as read-only.

### What was the solution? (How)

1.  Fixed up the documentation to clarify that developers should first attempt using the docker container test workflow. If that is not possible (e.g. unable to use Docker), then developers should inspect the Dockerfiles and replicate the setup on their development machine
2. Switched to using the `BUILDKIT_SANDBOX_HOSTNAME` ([ref docs](https://docs.docker.com/reference/dockerfile/#buildkit-built-in-build-args)) to specify the container hostname at build-time. [Buildkit](https://docs.docker.com/build/buildkit/) is the new default container image build backend for Docker version 23.0 and newer.

### What is the impact of this change?

Developers able to use more modern versions of Docker (&ge; 23.0)

### How was this change tested?

See [DEVELOPMENT.md](https://github.com/OpenJobDescription/openjd-model-for-python/blob/mainline/DEVELOPMENT.md#testing) for information on running tests.

- Ran the Linux automated tests using the documented Docker workflow and they passed

### Was this change documented?

The relevant developer documentation was updated:
- `DEVELOPMENT.md`
- `testing_containers/ldap_sudo_environment/README.md`

### Is this a breaking change?

No

### Does this change impact security?

No

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-09-18 14:57 UTC, AWS-Samuel approved these changes, later dismissed

2024-09-18 15:20 UTC, moorec-aws requested changes

2024-09-18 15:20 UTC, moorec-aws commented on DEVELOPMENT.md
> +The codebase contains cross-user impersonation tests that rely on the exitence of specific users and
```suggestion
The codebase contains cross-user impersonation tests that rely on the existence of specific users and
```

2024-09-19 14:24 UTC, jusiskin commented on DEVELOPMENT.md
> +The codebase contains cross-user impersonation tests that rely on the exitence of specific users and
Fixed, thanks!

2024-09-19 15:26 UTC, moorec-aws approved these changes

2024-09-19 16:39 UTC, AWS-Samuel approved these changes

2024-09-19 16:47 UTC, merged