chore: upgrade test containers from buster to bookworm and cache Python deps
OpenJobDescription/openjd-sessions-for-python pull request #178
Opened 2024-10-02 21:31 UTC by jusiskin

### What was the problem/requirement? (What/Why)

The developer scripting for test automation uses Docker to setup Linux containers used for cross-user test automation. There are two problems with this scripting:

1.  The scripting is not optimized for a rapid developer iteration loop. The `openjd-sessions` code is bind mounted when launching the container which means that the hatch environment must be created each time the tests are run.
2. The `Dockerfiles` build on the `python:3.7-buster` base container image. This container image is now end-of-life and a new image was last pushed a year ago (https://hub.docker.com/_/python/tags?name=3.9-buster)

### What was the solution? (How)

1. Refactor the `Dockerfile`s to build the hatch environment into the Docker image and not when running the container
2. Modify the `Dockerfile`s to use `python:3.7-bullseye`.
    1. This required adding `-y` to `apt-get install ...` commands in the `Dockerfile`s since this was a behavior change from buster to bullseye
    2. The `test_subprocess.py` test module needed to be modified due to a behavior change between the base images. Processes killed with signals are put in a "zombie" state if their parent is still running but hasn't checked the exit code of the process (see https://en.wikipedia.org/wiki/Zombie_process)

### What is the impact of this change?

1.  The developer iteration loop is faster
2. The container uses a base container image that is actively maintained and reflects an up-to-date environment

### How was this change tested?

See [DEVELOPMENT.md](https://github.com/OpenJobDescription/openjd-model-for-python/blob/mainline/DEVELOPMENT.md#testing) for information on running tests.

- Ran the unit tests which succeded
- Ran the cross-user Linux tests using the modified scripting documented in `DEVELOPER.md` which succeeded

### Was this change documented?

- Code comments were added were deemed fit and relevant READMEs were updated in the repository

### Is this a breaking change?

>   A breaking change is one that modifies a public contract in a way that is not backwards compatible. See the
[Public Interfaces](https://github.com/OpenJobDescription/openjd-model-for-python/blob/mainline/DEVELOPMENT.md#the-packages-public-interface) section
of the DEVELOPMENT.md for more information on the public contracts.

No, there were no breaking changes made

### Does this change impact security?

This change does not impact the threat model of the package 

This change improves the development-time security posture since developers will be using an actively maintained base container image.

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-11-12 15:40 UTC, crowecawcaw submitted a review, later dismissed

2024-11-12 20:35 UTC, ddneilson requested changes

2024-11-12 20:35 UTC, ddneilson commented on scripts/run_sudo_tests.sh
> +            DO_BUILD="True"
```suggestion
```

Looks like you got rid of all uses of `DO_BUILD`

2024-11-12 20:35 UTC, ddneilson commented on testing_containers/ldap_sudo_environment/Dockerfile
> +ARG PIP_INDEX_URL
Q: Have you tested this build without having `PIP_INDEX_URL` defined in your environment?

2024-11-12 20:35 UTC, ddneilson commented on testing_containers/ldap_sudo_environment/Dockerfile
> +COPY testing_containers/ldap_sudo_environment/changePassword.ldif /config
Question: Why the switch to fuller relative paths in the source filenames? This makes the Dockerfile less movable.

2024-11-12 20:40 UTC, jusiskin commented on testing_containers/ldap_sudo_environment/Dockerfile
> +COPY testing_containers/ldap_sudo_environment/changePassword.ldif /config
This was in order to copy the source tree into the container which removes file-system ownership (UID/GID) and permission coupling between the host machine and the container.

2024-11-12 20:41 UTC, jusiskin commented on testing_containers/ldap_sudo_environment/Dockerfile
> +ARG PIP_INDEX_URL
Just tested and the workflow succeeds end-to-end.

2024-11-12 20:54 UTC, jusiskin commented on scripts/run_sudo_tests.sh
> +            DO_BUILD="True"
Ah good catch. Removed this last occurrence.

2024-11-12 20:55 UTC, ddneilson commented on testing_containers/ldap_sudo_environment/Dockerfile
> +ARG PIP_INDEX_URL
Thank you!

2024-11-12 20:56 UTC, ddneilson approved these changes

2024-11-13 20:44 UTC, crowecawcaw approved these changes

2024-11-13 20:46 UTC, merged