test: Add Windows subprocess impersonation tests
OpenJobDescription/openjd-sessions-for-python pull request #72
Opened 2024-02-08 01:21 UTC by roblutt

### What was the problem/requirement? (What/Why)
We want the subprocess module to be unit tested for impersonation on Windows to ensure code quality.

### What was the solution? (How)
Add unit tests.

### What is the impact of this change?
All tests run locally. All tests except `test_notify_ends_process` run in Github Actions.

We'll investigate the `test_notify_ends_process` failure once #58 is merged.

****

### How was this change tested?
Unit tests pass.

### Was this change documented?
No

### Is this a breaking change?
No

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-02-08 19:15 UTC, ddneilson requested changes

2024-02-08 22:39 UTC, ddneilson submitted a review, later dismissed

2024-02-12 22:49 UTC, ddneilson submitted a review, later dismissed

2024-02-13 19:43 UTC, matta-aws commented on test/openjd/sessions/test_subprocess.py
> +            args=["powershell", "-command", f"python {str(python_app_loc)}"],
We don't need `powershell` here.  We can call python directly.  ([as in same user version](https://github.com/OpenJobDescription/openjd-sessions-for-python/pull/72))

2024-02-13 19:46 UTC, matta-aws commented on test/openjd/sessions/test_subprocess.py
> +            args=["powershell", "-Command", "python", str(python_app_loc)],
Same here.  Can just call python (sys.executable)

2024-02-13 19:49 UTC, matta-aws commented on test/openjd/sessions/test_subprocess.py
> +        # If there's no 9, then we ended before the app naturally finished.
nit:  19 (not 9)

2024-02-13 19:56 UTC, matta-aws commented on test/openjd/sessions/test_subprocess.py
> +        assert len(children) == 2  # .sh & .py scripts parented under 'sudo'
nit:  comment is posix oriented.  (no .sh script and no sudo on windows.)

2024-02-14 03:33 UTC, roblutt commented on test/openjd/sessions/test_subprocess.py
> +            args=["powershell", "-command", f"python {str(python_app_loc)}"],
Good point, changed

2024-02-14 03:33 UTC, roblutt commented on test/openjd/sessions/test_subprocess.py
> +        # If there's no 9, then we ended before the app naturally finished.
Fixed

2024-02-14 03:34 UTC, roblutt commented on test/openjd/sessions/test_subprocess.py
> +        assert len(children) == 2  # .sh & .py scripts parented under 'sudo'
Thanks, removed

2024-02-14 19:02 UTC, matta-aws approved these changes

2024-02-15 21:44 UTC, ddneilson approved these changes

2024-02-15 21:53 UTC, merged