feat(WIP): Sessions can now be run in a Windows Service context
OpenJobDescription/openjd-sessions-for-python pull request #97
Opened 2024-02-27 03:56 UTC by ddneilson

### What was the problem/requirement? (What/Why)

Windows requires the use of different Win32 APIs to impersonate users when you're running in the context of a Service (Windows Session ID 0) than if you're running in an interactive logon session. The current code uses `CreateProcessWithLogonW` to do impersonation, and that API does not work inside Session 0.

### What was the solution? (How)

Detect when we are running in Session 0, and make use of `CreateProcessAsUserW`. To support this we require that the caller of this library create the `WindowsSessionUser` using the handle to a logon token that they create with the Win32 APIs rather than with a password directly.

### What is the impact of this change?

Users of the library should be able to successfully run Sessions, with impersonation, while running within a Windows Service context.

### How was this change tested?

I've enhanced the testing notes in the DEVELOPMENT.md with instructions regarding how to test the impersonation logic in Windows. I've followed these instructions by creating an `actions` user on my workstation as the target to impersonate during tests.

Testing checklist:

- [ ] Interactive logon session: `hatch run test` passes with `OPENJD_TEST_WIN_USER_NAME` and `OPENJD_TEST_WIN_USER_PASSWORD` defined.
- [ ] Service session: `hatch run test` passes with `OPENJD_TEST_WIN_USER_NAME` and `OPENJD_TEST_WIN_USER_PASSWORD` defined.

### Was this change documented?

Yes, I have added information to the README on how to run Sessions with impersonation.

### Is this a breaking change?

No, not intentionally.

----

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-02-27 04:12 UTC, ddneilson commented on src/openjd/sessions/_session_user.py
>  class WindowsSessionUser(SessionUser):
TODO - I need to add information to the docstring regarding the requirements of this class w.r.t. Session 0 and Session not-0.

2024-02-28 01:55 UTC, ddneilson commented on src/openjd/sessions/_subprocess.py
> +            # if is_windows():
TODO - I wanted to test if we can pass this in all Windows-based cases, rather than just the impersonation cases.

2024-02-28 01:56 UTC, ddneilson commented on src/openjd/sessions/_win32/_api.py
> +# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
TODO - Prune the uneccessary things from this file; it defines way more APIs and constants than we actually use

2024-03-01 16:17 UTC, ddneilson commented on src/openjd/sessions/_win32/_api.py
> +# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
This defines more APIs than we actually use. No harm in it, and I'm inclined to leave them in in case they're useful in the future.

2024-03-01 16:26 UTC, ddneilson commented on src/openjd/sessions/_win32/_popen_as_user.py
> +# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
This is not net-new. It is moved from `src/openjd/sessions/_popen_windows_as_user.py`

2024-03-01 16:29 UTC, ddneilson commented on test/openjd/sessions/test_subprocess.py
> +            for _ in range(20):
This style of test was experiencing some races, so I just cleaned up all that had this style.

2024-03-01 16:31 UTC, ddneilson commented on src/openjd/sessions/_runner_base.py
> +        # Check on the state of the future for done/canceled first
I discovered a timing bug in this `state` method during testing. If we cancel an action then we'd actually see the state go from `RUNNING -> CANCELING -> RUNNING -> CANCELED`, but we should only see `RUNNING -> CANCELING -> CANCELED`. Similar for TIMEOUT terminal state; we should only see `RUNNING -> CANCELING -> TIMEOUT`

2024-03-01 17:12 UTC, ddneilson commented on src/openjd/sessions/_subprocess.py
> +        if False:  # self._user is None:
TODO - This is some leftover testing stuff. I'll clean this up.

2024-03-01 17:37 UTC, ddneilson commented on src/openjd/sessions/_win32/_api.py
> +        malloc_size_in_bytes = ctypes.sizeof(TOKEN_PRIVILEGES) + 2 * ctypes.sizeof(
The `2 * ctypes.sizeof(...)` should be `length * ctypes.sizeof(...)`

Will fix.

2024-03-04 23:36 UTC, jericht commented on README.md
> +2. Provide a way for you to oermit access, on a per-Session basis, to specific local and
```suggestion
2. Provide a way for you to permit access, on a per-Session basis, to specific local and
```

2024-03-04 23:36 UTC, jericht commented on README.md
> +as follow:
```suggestion
To run an impersonated Session on POSIX Systems, modify the "Running a Session" example
as follows:
```

2024-03-04 23:36 UTC, jericht commented on README.md
> +as follow:
```suggestion
To run an impersonated Session on Windows Systems, modify the "Running a Session" example
as follows:
```

2024-03-04 23:36 UTC, jericht commented on src/openjd/sessions/_runner_base.py
> +from ._os_checker import is_posix  # , is_windows
nit: commented out code
```suggestion
from ._os_checker import is_posix
```

2024-03-04 23:36 UTC, jericht commented on src/openjd/sessions/_session_user.py
> +                Defaults to the username if not provided.
> Defaults to the username if not provided.

This code was already here before this PR, but just wondering: does Windows automatically create a group with the same name as a new user that is created? If not, should we leave this field as empty if not provided? (I haven't seen this behavior in my local testing using powershell's `New-LocalUser` cmdlet)

2024-03-04 23:36 UTC, jericht commented on src/openjd/sessions/_subprocess.py
> +        except Exception as e:
Is going from catching `OSError` to `Exception` intentional?

2024-03-04 23:36 UTC, jericht commented on src/openjd/sessions/_win32/_helpers.py
> +            raise WinError()
> WARNING! DO NOT USE THIS

Can we delete this function?

2024-03-04 23:36 UTC, jericht commented on src/openjd/sessions/_win32/_helpers.py
> +    """Converts a Python dictionary representation of an environment into a character beffer as expected by the
```suggestion
    """Converts a Python dictionary representation of an environment into a character buffer as expected by the
```

2024-03-04 23:36 UTC, jericht commented on src/openjd/sessions/_win32/_helpers.py
> +        adjust_privileges(privilege_constants, False)
If the process already has the privileges before making this call, it looks like this would disable those privileges. Should we first get the existing privilege enabled/disabled array, then restore the system to that state in the `finally` block?

2024-03-04 23:36 UTC, jericht commented on test/openjd/sessions/test_runner_step_script.py
> +# from openjd.sessions._os_checker import is_windows
nit: commented out code

2024-03-04 23:49 UTC, ddneilson commented on src/openjd/sessions/_win32/_helpers.py
> +            raise WinError()
Hah. Actually, I need to delete the warning. :-) I fixed the issue

2024-03-04 23:51 UTC, ddneilson commented on src/openjd/sessions/_win32/_helpers.py
> +        adjust_privileges(privilege_constants, False)
Good thinking. I had the same thought as well. Given that the only current use-case of this function is gaining the backup/restore privileges when loading an user profile, which is itself unused code, I think that we can take the idea on as a future TODO when/if this code goes live.

Alternatively, I can just delete this helper & the user profile loader entirely....

2024-03-04 23:57 UTC, ddneilson commented on src/openjd/sessions/_subprocess.py
> +        except Exception as e:
Yeah, it was intentional. I generally don't like the generic exception catch, but I noticed that if we got unaccounted-for exception types here then we don't properly report the state of the running action via the callback mechanism. So consumers that rely on that callback to hear about state changes will think that the action is running forever.

2024-03-04 23:58 UTC, ddneilson commented on src/openjd/sessions/_session_user.py
> +                Defaults to the username if not provided.
Windows does not. You're right that the default should change here; it shouldn't set any group ACLs if not provided.

2024-03-05 14:44 UTC, ddneilson commented on src/openjd/sessions/_session_user.py
> +                Defaults to the username if not provided.
Dug a bit. This would be a breaking change. I agree that it should change, but let's do it in a follow-up so as to not turn this PR into more of a monster. :-)

2024-03-05 18:17 UTC, jericht submitted a review, later dismissed

2024-03-05 19:51 UTC, jusiskin requested changes

2024-03-05 19:51 UTC, jusiskin commented on test/openjd/sessions/test_runner_base.py
> +            while runner.state in ScriptRunnerState.CANCELING:
Did we mean:

```suggestion
            while runner.state == ScriptRunnerState.CANCELING:
```

2024-03-05 19:51 UTC, jusiskin commented on src/openjd/sessions/_win32/_helpers.py
> +    lp_environment: Optional[c_void_p] = None
nit: this one is missing a docstring

2024-03-05 19:51 UTC, jusiskin commented on src/openjd/sessions/_win32/_popen_as_user.py
> +    )
Can this check be done in a more local way? Having this run on module load seems too strict. Consumers of the library would see the error when importing the module as opposed to when they use the incompatible APIs.

2024-03-05 19:51 UTC, jusiskin commented on src/openjd/sessions/_subprocess.py
> +        del proc
should this be in a `finally` block?

2024-03-05 20:23 UTC, ddneilson commented on test/openjd/sessions/test_runner_base.py
> +            while runner.state in ScriptRunnerState.CANCELING:
Yes. Fixing. Thanks for spotting that!

2024-03-05 20:23 UTC, ddneilson commented on src/openjd/sessions/_win32/_popen_as_user.py
> +    )
Discussed offline. Fine as-is. :-)

2024-03-05 20:28 UTC, ddneilson commented on src/openjd/sessions/_subprocess.py
> +        del proc
Right you are, good eye. The callback could raise an exception. If it does then we wouldn't cleanup.

2024-03-05 20:40 UTC, jericht commented on src/openjd/sessions/_subprocess.py
> +        del proc
I saw this as well but then thought the "GC would handle it anyway", but I just did a quick Google and found out you can actually [disable the GC](https://docs.python.org/3/library/gc.html#gc.disable), so we definitely do need this.

2024-03-05 20:41 UTC, jericht approved these changes

2024-03-05 21:50 UTC, jusiskin approved these changes

2024-03-05 21:52 UTC, merged